version: "3"
services:
  ml-wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: ml-wrapper-container
    volumes:
      - /usr/app/models
      - .:/usr/app
