---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lighthouse
  name: lighthouse-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lighthouse-server
  template:
    metadata:
      labels:
        app: lighthouse-server
    spec:
      containers:
        - name: app
          image: ghcr.io/light-house-ai/lighthouse-server:latest
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: api-port
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: LIGHTHOUSE_HOST
              value: "0.0.0.0"
            - name: LIGHTHOUSE_WORKERS_COUNT
              value: "10"
            - name: LIGHTHOUSE_DB_HOST
              value: "lighthouse-db-service"
            - name: LIGHTHOUSE_REDIS_HOST
              value: "lighthouse-redis-service"
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
          ports:
            - containerPort: 8000
              name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: lighthouse
  name: lighthouse-server-service
spec:
  selector:
    app: lighthouse-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
      name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lighthouse-server
  namespace: lighthouse
  labels:
    name: lighthouse-server
spec:
  rules:
    - host: lighthouse.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: lighthouse-server-service
                port:
                  name: api-port

---
