apiVersion: v1
kind: Service
metadata:
  name: model-nginx-service
spec:
  type: NodePort
  selector:
    app: model-deployment
  ports:
    - port: 8080
      targetPort: 8000
      nodePort: 31515
      protocol: TCP
      name: http
