apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-deployment
  template:
    metadata:
      labels:
        app: model-deployment
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: model
          image: aayman1/wrapper:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          #env:
          # - name: AZURE_STORAGE_CONNECTION
          #   valueFrom:
          #     secretKeyRef:
          #       name: azure-storage-secret
          #       key: AZURE_STORAGE_CONNECTION
          # - name: CONTAINER_NAME
          #   value: models
          # - name: MODEL_ID
          #   value: "${MODEL_ID}"
          # - name: MODEL_VERSION
          #   value: "${MODEL_VERSION}"
          # - name: MODEL_EXTENSION
          #   value: "${MODEL_EXTENSION}"
