version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  mongo:
    image: mongo:4.0.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=lighthouse
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  
  lighthouse_server:
    build:
      context: ../server/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file: ../server/.env
    depends_on:
      - db
      - mongo

volumes:
  db:
    driver: local
  mongo:
    driver: local