version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes: 
      - db:/var/lib/postgresql/data

  mongo:
    image: mongo:4.0.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo:/data/db
  
  redis-celery:
    image: redis:7.0.1-alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nn-generator:
    build:
      context: ../nn_generator/
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - BROKER_URL=redis://:${REDIS_PASSWORD}@redis-celery:${REDIS_PORT}/0
      - RESULTS_BACKEND_URL=redis://:${REDIS_PASSWORD}@redis-celery:${REDIS_PORT}/0
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
      - WEBHOOK_URL=http://lighthouse-server:${SERVER_PORT}/api/v1/models/{model_id}/training_status/
    depends_on:
      - redis-celery

  lighthouse-server:
    build:
      context: ../server/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DEBUG=${DEBUG}
      - PORT=${SERVER_PORT}
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
      - CELERY_BACKEND_URL=redis://:${REDIS_PASSWORD}@redis-celery:${REDIS_PORT}/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis-celery:${REDIS_PORT}/0
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/postgres
    depends_on:
      - db
      - mongo

volumes:
  db:
    driver: local
  mongo:
    driver: local
  redis:
    driver: local