"""add model training status

Revision ID: 01710116278d
Revises: 47a9fefc88d8
Create Date: 2022-06-09 12:11:29.423642

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '01710116278d'
down_revision = '47a9fefc88d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'model',
        sa.Column('is_trained',
                  sa.Boolean(),
                  nullable=False,
                  server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'is_trained')
    # ### end Alembic commands ###
