"""add indexes on foreign keys

Revision ID: 47a9fefc88d8
Revises: ce749016e7b5
Create Date: 2022-06-09 04:50:38.564262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a9fefc88d8'
down_revision = 'ce749016e7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cleaned_dataset_project_id'), 'cleaned_dataset', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployment_primary_model_id'), 'deployment', ['primary_model_id'], unique=False)
    op.create_index(op.f('ix_deployment_project_id'), 'deployment', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployment_secondary_model_id'), 'deployment', ['secondary_model_id'], unique=False)
    op.create_index(op.f('ix_model_dataset_id'), 'model', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_model_project_id'), 'model', ['project_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_index(op.f('ix_raw_dataset_project_id'), 'raw_dataset', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_dataset_project_id'), table_name='raw_dataset')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_model_project_id'), table_name='model')
    op.drop_index(op.f('ix_model_dataset_id'), table_name='model')
    op.drop_index(op.f('ix_deployment_secondary_model_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_project_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_primary_model_id'), table_name='deployment')
    op.drop_index(op.f('ix_cleaned_dataset_project_id'), table_name='cleaned_dataset')
    # ### end Alembic commands ###
