"""add project overview & model metrics

Revision ID: 49c9abfbbab1
Revises: 5268b7eeb570
Create Date: 2022-06-12 21:41:06.859087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c9abfbbab1'
down_revision = '5268b7eeb570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('accuracy_score', sa.Float(), nullable=True))
    op.add_column('model', sa.Column('mean_squared_log_error', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('overview', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'overview')
    op.drop_column('model', 'mean_squared_log_error')
    op.drop_column('model', 'accuracy_score')
    # ### end Alembic commands ###
