"""add models training parameters

Revision ID: 5268b7eeb570
Revises: 01710116278d
Create Date: 2022-06-12 21:04:42.455284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5268b7eeb570'
down_revision = '01710116278d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('number_of_layers', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('maximum_neurons_per_layer', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('learning_rate', sa.Float(), nullable=True))
    op.add_column('model', sa.Column('batch_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'batch_size')
    op.drop_column('model', 'learning_rate')
    op.drop_column('model', 'maximum_neurons_per_layer')
    op.drop_column('model', 'number_of_layers')
    # ### end Alembic commands ###
