"""add deployment notification status

Revision ID: 94deb3e05eb3
Revises: 9e4e53dba4ba
Create Date: 2022-06-17 21:44:28.009283

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '94deb3e05eb3'
down_revision = '9e4e53dba4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'deployment',
        sa.Column('has_monitoring_notification',
                  sa.Boolean(),
                  nullable=False,
                  server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'has_monitoring_notification')
    # ### end Alembic commands ###
