"""create deployment & data models

Revision ID: 9ca536a0a427
Revises: 494ce7c3b889
Create Date: 2022-05-19 04:17:22.974219

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca536a0a427'
down_revision = '494ce7c3b889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('version', 'project_id')
    )    
    op.add_column('model', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('model', sa.Column('data_version', sa.Integer(), nullable=False))
    op.add_column('model', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('model_project_id_fkey', 'model', type_='foreignkey')
    op.create_foreign_key('model_project_id_data_version_fkey', 'model', 'data', ['project_id', 'data_version'], ['project_id', 'version'])
    op.create_foreign_key('model_project_id_fkey', 'model', 'project', ['project_id'], ['id'])
    op.drop_column('model', 'id')
    op.create_primary_key('model_pkey', 'model', ['project_id', 'version'])
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('deployment_type', sa.Enum('champion_challenger', 'single_model', 'fallback', name='deploymenttype'), nullable=False, default='single_model'),
    sa.Column('primary_model_version', sa.Integer(), nullable=False),
    sa.Column('secondary_model_version', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False, default=False),
    sa.ForeignKeyConstraint(['project_id', 'primary_model_version'], ['model.project_id', 'model.version'], name='deployment_project_id_primary_model_version_fkey'),
    sa.ForeignKeyConstraint(['project_id', 'secondary_model_version'], ['model.project_id', 'model.version'], name='deployment_project_id_secondary_model_version_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('model_project_id_data_version_fkey', 'model', type_='foreignkey')
    op.drop_constraint('deployment_project_id_primary_model_version_fkey', 'deployment', type_='foreignkey')
    op.drop_constraint('deployment_project_id_secondary_model_version_fkey', 'deployment', type_='foreignkey')
    op.create_foreign_key('model_project_id_fkey', 'model', 'project', ['project_id'], ['id'])
    op.drop_column('model', 'date_created')
    op.drop_column('model', 'data_version')
    op.drop_column('model', 'version')
    op.drop_table('deployment')
    op.drop_table('data')
    sa.Enum(name='deploymenttype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
