"""edit notifications table

Revision ID: 9dd6f048dff7
Revises: 49c9abfbbab1
Create Date: 2022-06-13 06:50:35.679320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd6f048dff7'
down_revision = '49c9abfbbab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notification', sa.Column('body', sa.String(), nullable=False))
    op.drop_column('notification', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notification', 'body')
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###
