"""change deployment type column name

Revision ID: 9e4e53dba4ba
Revises: 9dd6f048dff7
Create Date: 2022-06-13 07:43:28.853760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e4e53dba4ba'
down_revision = '9dd6f048dff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('type', sa.Enum('champion_challenger', 'single_model', 'fallback', name='deploymenttype'), nullable=False))
    op.drop_column('deployment', 'deployment_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('deployment_type', postgresql.ENUM('champion_challenger', 'single_model', 'fallback', name='deploymenttype'), autoincrement=False, nullable=False))
    op.drop_column('deployment', 'type')
    # ### end Alembic commands ###
