"""add predicted_column to projects

Revision ID: cc84da773ef2
Revises: 61daee7c09ed
Create Date: 2022-06-09 04:38:07.214985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc84da773ef2'
down_revision = '61daee7c09ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('predicted_column', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'predicted_column')
    # ### end Alembic commands ###
