"""add project type to project model

Revision ID: d41bcad37308
Revises: de97f321651a
Create Date: 2022-05-20 19:43:54.654791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd41bcad37308'
down_revision = 'de97f321651a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    project_type = postgresql.ENUM('classification', 'regression', name='projecttype')
    project_type.create(op.get_bind())
    op.add_column('project', sa.Column('type', sa.Enum('classification', 'regression', name='projecttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'type')
    project_type = postgresql.ENUM('classification', 'regression', name='projecttype')
    project_type.drop(op.get_bind())
    # ### end Alembic commands ###
