version: "3"
services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: wrapper-dev-container
    volumes:
      # - ./usr/app/models
      - .:/usr/app
