# Constants file
# * GENERAL CONSTANTS
PKL_EXTENTION = ".pkl"
IMAGE_NAME = "aayman1/wrapper:latest"
CONTAINER_NAME = "models"
CLUSTER_NAMESPACE = "default"
# * CLUSTER_IP CONSTANTS
DEFAULT_CLUSTER_IP_PORT = 8000
DEFAULT_CLUSTER_IP_TARGET_PORT = 8000
# * INGRESS CONSTANTS
INGRESS_NAME = "models-ingress"
INGRESS_CLASS = "nginx"
# * DEFAULT DEPLOYMENT CONSTANTS
DEFAULT_IMAGE_NAME = "aayman1/wrapper:latest"
DEFAULT_DEPLOYMENT_NAME = "default"
